apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: externaltasksblobstore
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: "firstacastgrmoreirao"
  - name: storageAccessKey
    value: "YcmFkOrbqZ9nQLwEsg9k5Dbn75hYWUrHHu01HmnSI3pZfcKQzdozOUaKCLh5s1F9e4/fzObZ9u+P+AStulKKbg==" 
  - name: container
    value: "externaltaskscontainer"
  - name: decodeBase64
    value: false