apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: externaltasksblobstore
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: "firstacastgrmoreirao"
  - name: storageAccessKey
    value: "<stgkeyhere>" 
  - name: container
    value: "externaltaskscontainer"
  - name: decodeBase64
    value: false