name: tasksmanager-frontend-webapp deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/FirstACAApp/FirstACAAppClient/**'
    - '.github/workflows/build-deploy-client.yaml'

  # Allow mannually trigger 
  workflow_dispatch:      

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: taskstrackeracrrmoreirao.azurecr.io
          username: ${{ secrets.TASKSMANAGER_REGISTRY_USERNAME }}
          password: ${{ secrets.TASKSMANAGER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: taskstrackeracrrmoreirao.azurecr.io/tasksmanager-frontend-webapp:${{ github.sha }} , taskstrackeracrrmoreirao.azurecr.io/tasksmanager-frontend-webapp:latest
          file: src/FirstACAApp/FirstACAAppClient/Dockerfile
          context: src/FirstACAApp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
   
    steps:
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tasksmanager-frontend-webapp -g tasks-tracker-rg --server taskstrackeracrrmoreirao.azurecr.io --username  ${{ secrets.TASKSMANAGER_REGISTRY_USERNAME }} --password ${{ secrets.TASKSMANAGER_REGISTRY_PASSWORD }}
            az containerapp update -n tasksmanager-frontend-webapp -g tasks-tracker-rg --image taskstrackeracrrmoreirao.azurecr.io/tasksmanager-frontend-webapp:${{ github.sha }}